# Generated by Django 3.1 on 2022-04-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='apt',
            new_name='apartment',
        ),
    ]
